// flow-typed signature: 3a082142e6dc83a182a4412892f196af
// flow-typed version: <<STUB>>/lodash.startswith_v^4.2.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.startswith'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.startswith' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.startswith/index' {
  declare module.exports: $Exports<'lodash.startswith'>;
}
declare module 'lodash.startswith/index.js' {
  declare module.exports: $Exports<'lodash.startswith'>;
}
