// flow-typed signature: 699ce7f8da924e3869afb7b4bd623214
// flow-typed version: <<STUB>>/tapava_v^2.3.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tapava'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tapava' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tapava/dist/index' {
  declare module.exports: any;
}

declare module 'tapava/dist/test' {
  declare module.exports: any;
}

declare module 'tapava/dist/throws-promise' {
  declare module.exports: any;
}

declare module 'tapava/lib/index' {
  declare module.exports: any;
}

declare module 'tapava/lib/test' {
  declare module.exports: any;
}

declare module 'tapava/lib/throws-promise' {
  declare module.exports: any;
}

declare module 'tapava/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tapava/dist/index.js' {
  declare module.exports: $Exports<'tapava/dist/index'>;
}
declare module 'tapava/dist/test.js' {
  declare module.exports: $Exports<'tapava/dist/test'>;
}
declare module 'tapava/dist/throws-promise.js' {
  declare module.exports: $Exports<'tapava/dist/throws-promise'>;
}
declare module 'tapava/lib/index.js' {
  declare module.exports: $Exports<'tapava/lib/index'>;
}
declare module 'tapava/lib/test.js' {
  declare module.exports: $Exports<'tapava/lib/test'>;
}
declare module 'tapava/lib/throws-promise.js' {
  declare module.exports: $Exports<'tapava/lib/throws-promise'>;
}
declare module 'tapava/test.js' {
  declare module.exports: $Exports<'tapava/test'>;
}
